version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: swiftparserdb
      MYSQL_USER: swiftuser
      MYSQL_PASSWORD: swiftpass
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: swiftcode-app
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    volumes:
      - ./swift_codes.csv:/app/swift_codes.csv
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/swiftparserdb
      SPRING_DATASOURCE_USERNAME: swiftuser
      SPRING_DATASOURCE_PASSWORD: swiftpass

  test:
    image: maven:3.9.5-eclipse-temurin-17
    container_name: swiftcode-tests
    depends_on:
      - db
    volumes:
      - .:/app
    working_dir: /app
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/swiftparserdb
      SPRING_DATASOURCE_USERNAME: swiftuser
      SPRING_DATASOURCE_PASSWORD: swiftpass
    command: mvn test

volumes:
  db_data:
